name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      headed:
        description: 'Run in headed mode'
        type: boolean
        default: false
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright
      run: npx playwright install
    
    # Essential Xvfb setup for headed mode
    - name: Setup Xvfb environment
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgbm-dev libxshmfence-dev
        echo "DISPLAY=:99" >> $GITHUB_ENV
        echo "HEADLESS=${{ !(github.event_name == 'workflow_dispatch' && inputs.headed) }}" >> $GITHUB_ENV
    
    # Start Xvfb server (required for both modes for consistency)
    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1280x1024x24 -ac +extension GLX +render -noreset &
        sleep 3
        ps aux | grep Xvfb
    
    # Run tests with proper environment
    - name: Run Playwright tests
      run: npm test
      env:
        DISPLAY: ${{ env.DISPLAY }}
        HEADLESS: ${{ env.HEADLESS }}
        PWDEBUG: ${{ env.HEADLESS == 'false' && '1' || '0' }}
    
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/